package cn.zhang.com.mapper;

import cn.zhang.com.model.cc;
import cn.zhang.com.model.ccExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ccMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Tue Jan 28 17:10:37 CST 2020
     */
    long countByExample(ccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Tue Jan 28 17:10:37 CST 2020
     */
    int deleteByExample(ccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Tue Jan 28 17:10:37 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Tue Jan 28 17:10:37 CST 2020
     */
    int insert(cc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Tue Jan 28 17:10:37 CST 2020
     */
    int insertSelective(cc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Tue Jan 28 17:10:37 CST 2020
     */
    List<cc> selectByExampleWithRowbounds(ccExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Tue Jan 28 17:10:37 CST 2020
     */
    List<cc> selectByExample(ccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Tue Jan 28 17:10:37 CST 2020
     */
    cc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Tue Jan 28 17:10:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") cc record, @Param("example") ccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Tue Jan 28 17:10:37 CST 2020
     */
    int updateByExample(@Param("record") cc record, @Param("example") ccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Tue Jan 28 17:10:37 CST 2020
     */
    int updateByPrimaryKeySelective(cc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Tue Jan 28 17:10:37 CST 2020
     */
    int updateByPrimaryKey(cc record);
}