package cn.zhang.com.mapper;

import cn.zhang.com.model.NotiFication;
import cn.zhang.com.model.NotiFicationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface NotiFicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    long countByExample(NotiFicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    int deleteByExample(NotiFicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    int insert(NotiFication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    int insertSelective(NotiFication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    List<NotiFication> selectByExampleWithRowbounds(NotiFicationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    List<NotiFication> selectByExample(NotiFicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    NotiFication selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") NotiFication record, @Param("example") NotiFicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    int updateByExample(@Param("record") NotiFication record, @Param("example") NotiFicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    int updateByPrimaryKeySelective(NotiFication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    int updateByPrimaryKey(NotiFication record);
}