package cn.zhang.com.model;

public class Dianzan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianzan.id
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianzan.notifier
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    private Long notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianzan.outerid
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    private Long outerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianzan.zhaunttai
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    private Integer zhaunttai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianzan.TYPE
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dianzan.gmt_create
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianzan.id
     *
     * @return the value of dianzan.id
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianzan.id
     *
     * @param id the value for dianzan.id
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianzan.notifier
     *
     * @return the value of dianzan.notifier
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    public Long getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianzan.notifier
     *
     * @param notifier the value for dianzan.notifier
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    public void setNotifier(Long notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianzan.outerid
     *
     * @return the value of dianzan.outerid
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    public Long getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianzan.outerid
     *
     * @param outerid the value for dianzan.outerid
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    public void setOuterid(Long outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianzan.zhaunttai
     *
     * @return the value of dianzan.zhaunttai
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    public Integer getZhaunttai() {
        return zhaunttai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianzan.zhaunttai
     *
     * @param zhaunttai the value for dianzan.zhaunttai
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    public void setZhaunttai(Integer zhaunttai) {
        this.zhaunttai = zhaunttai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianzan.TYPE
     *
     * @return the value of dianzan.TYPE
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianzan.TYPE
     *
     * @param type the value for dianzan.TYPE
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dianzan.gmt_create
     *
     * @return the value of dianzan.gmt_create
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dianzan.gmt_create
     *
     * @param gmtCreate the value for dianzan.gmt_create
     *
     * @mbg.generated Tue Feb 25 20:45:06 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}